/**
 * This file is autogenerated by scaffold-stylus.
 * You should not edit it manually or your changes might be overwritten.
 */
import type { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";

const deployedContracts = {
  421614: {
    PortfolioReader: {
      address: "0xf6caf1aff09b369e196034eecde33699cb3fd765",
      abi: [
        {
          type: "function",
          name: "getTokenBalance",
          inputs: [
            { name: "user", type: "address", internalType: "address" },
            { name: "token", type: "address", internalType: "address" },
          ],
          outputs: [
            { name: "", type: "address", internalType: "address" },
            { name: "", type: "uint256", internalType: "uint256" },
            { name: "", type: "uint8", internalType: "uint8" },
            { name: "", type: "string", internalType: "string" },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserPortfolio",
          inputs: [
            { name: "user", type: "address", internalType: "address" },
            { name: "tokens", type: "address[]", internalType: "address[]" },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct TokenBalance[]",
              components: [
                { name: "", type: "address", internalType: "address" },
                { name: "", type: "uint256", internalType: "uint256" },
                { name: "", type: "uint8", internalType: "uint8" },
                { name: "", type: "string", internalType: "string" },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNonZeroBalances",
          inputs: [
            { name: "user", type: "address", internalType: "address" },
            { name: "tokens", type: "address[]", internalType: "address[]" },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct TokenBalance[]",
              components: [
                { name: "", type: "address", internalType: "address" },
                { name: "", type: "uint256", internalType: "uint256" },
                { name: "", type: "uint8", internalType: "uint8" },
                { name: "", type: "string", internalType: "string" },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPortfolioBalances",
          inputs: [{ name: "user", type: "address", internalType: "address" }],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct TokenBalance[]",
              components: [
                { name: "", type: "address", internalType: "address" },
                { name: "", type: "uint256", internalType: "uint256" },
                { name: "", type: "uint8", internalType: "uint8" },
                { name: "", type: "string", internalType: "string" },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getVersion",
          inputs: [],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
      ],
    },
  },
} as const satisfies GenericContractsDeclaration;

export default deployedContracts;
